framework: jasmine
preMerge:
  pattern:
    - "spec/**/*.js"
postMerge:
  pattern:
    - "spec/**/*.js"
preRun: 
  command:
    - npm ci
    - npm install -g npm@8.12.1
postRun:
  command: 
    - echo 'Done Testing'
